#!/bin/bash
set -x
. config
#  Package sd2xmltv as a kodi addon that can be installed from a zip file
#
rm -rf tools.module.sd2xmltv
rm -rf unpack
rm tools.module.sd2xmltv-*.zip
mkdir tools.module.sd2xmltv
cp -r base_addon/* tools.module.sd2xmltv
#
#  Populate the addon
#
mkdir tools.module.sd2xmltv/libschedulesdirect/
cp -r ../libschedulesdirect/* tools.module.sd2xmltv/libschedulesdirect/
mkdir tools.module.sd2xmltv/xmltv/
cp -r ../xmltv/* tools.module.sd2xmltv/xmltv/
cp ../*.py tools.module.sd2xmltv/
cp ../logging.cfg tools.module.sd2xmltv/
mkdir tools.module.sd2xmltv/libhdhomerun/
cp -r ../libhdhomerun/* tools.module.sd2xmltv/libhdhomerun/
mkdir tools.module.sd2xmltv/utils/
cp -r ../utils/* tools.module.sd2xmltv/utils/
#  add the license files to keep everything on the up-n-up
cp ../LICENSE  tools.module.sd2xmltv/LICENSE-sd2xmltv
#
# update the addon version number
sed -i tools.module.sd2xmltv/addon.xml -e 's/__VER__/'${ADDON_VERSION}'/g'
zip -r tools.module.sd2xmltv-${ADDON_VERSION}.zip tools.module.sd2xmltv/
exit 0
